# db_connection_manager.pyi

class DB_Connection:
    def __init__(self, file_path: str = ..., initial_values=None, default=None) -> None: ...
    
    def set_user(self, user_key: str) -> None: ...
    
    def _setup_connection(self) -> None: ...
    
    def connect_n_cursor(self): ...
    
    def daten_spalten(self, query: str): ...
    
    def tabellen_ausgabe(self, data=None, header=None): ...
